import type { Metadata } from "next";
import { cookies } from "next/headers";
import { fontVariableClasses } from "./fonts";
import "./globals.css";
import "./design-system.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const savedTheme = (await cookies()).get("theme")?.value;
  const theme = savedTheme === "dark" ? "dark" : "light";

  return (
    <html
      lang="en"
      className={`${fontVariableClasses.join(" ")} antialiased`}
      data-theme={theme}
      style={{ colorScheme: theme }}
    >
      <body>{children}</body>
    </html>
  );
}
