import type { Metadata } from "next";
import { cookies } from "next/headers";
import { fontVariableClasses } from "./fonts";
import "./globals.css";
import "./design-system.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const themeInitializationScript = `
  (() => {
    const root = document.documentElement;

    if (!root.dataset.theme) {
      const theme = window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";

      root.dataset.theme = theme;
      root.style.colorScheme = theme;
    }
  })();
`;

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const themeCookie = (await cookies()).get("theme")?.value;
  const savedTheme =
    themeCookie === "light" || themeCookie === "dark" ? themeCookie : undefined;

  return (
    <html
      lang="en"
      className={`${fontVariableClasses.join(" ")} antialiased`}
      data-theme={savedTheme}
      style={savedTheme ? { colorScheme: savedTheme } : undefined}
      suppressHydrationWarning
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitializationScript }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
